### ISSUE TITLE
`@ctix-declaration` does not respect the include option and is incorrectly formatted

### ISSUE THREAD

**Issue by smallmain** [imjuni/ctix#158]
[ctix-demo.zip](https://github.com/user-attachments/files/16677550/ctix-demo.zip)

1. Take a look at the `index.ts` file:

```ts
import "./do.js"import "./test.js"
```

Missing ';' and line breaks, which should be:

```ts
import "./do.js";
import "./test.js";
```

2. Take a look at the `.ctirc` file:

```json
"include": [
  "**/*do*"
]
```

Should be only `do.ts` included, but `test.ts` is included anyway.

**Comment by imjuni** [comment]
@smallmain 

Thank you for your dedicated contribution. This issue was fixed in version `2.6.3`.

**Comment by imjuni** [comment]
@smallmain Hi,

Thank you for waiting!

![ctix](https://github.com/user-attachments/assets/1732d44e-960b-4b61-8243-0f03cff3b819)

The include/exclude option mechanisms follow the diagram as shown. The @ctix-declaration comment directive is designed to work only for files included in the include option. If the @ctix-declaration directive is added to files that are not included, it will not work. In version v2.6.2, the @ctix-declaration directive worked differently than intended, but this issue was fixed in v2.6.3. We apologize for the inconvenience. Is it still working differently from the design?

**Comment by smallmain** [comment]
> @smallmain Hi,
> 
> Thank you for waiting!
> 
> ![ctix](https://private-user-images.githubusercontent.com/1166575/364590041-1732d44e-960b-4b61-8243-0f03cff3b819.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MDE0MTIsIm5iZiI6MTcyNTUwMTExMiwicGF0aCI6Ii8xMTY2NTc1LzM2NDU5MDA0MS0xNzMyZDQ0ZS05NjBiLTRiNjEtODI0My0wZjAzY2ZmM2I4MTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMDE1MTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTk0NzM4MmJhMmEyM2MxYTliZTAyNmJlMWNiYTAzNDc2NzdjMGQyMDg3NzA4Yzc3ZDIxODZlYWY5NWUxMGNhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UqJUIgf9ZiGIgmJQ-h9Z_gCr3_WDtsNDFkPOkGl5uC8)
> 
> The include/exclude option mechanisms follow the diagram as shown. The @ctix-declaration comment directive is designed to work only for files included in the include option. If the @ctix-declaration directive is added to files that are not included, it will not work. In version v2.6.2, the @ctix-declaration directive worked differently than intended, but this issue was fixed in v2.6.3. We apologize for the inconvenience. Is it still working differently from the design?

@imjuni 
Yes, in 2.6.3 the problem still exists, will the above demo project 's ctix updated to 2.6.3, the `test.js` import is still generated, but the `include` does not include the file.

**Comment by imjuni** [comment]
@smallmain 

I tested your reproducible repository, where the include option was set to ["**/*do*"] and the exclude option to ["**check**"]. As a result, the do.ts file was added due to the include option, and the check.ts and check2.ts files were excluded by the exclude option. In this case, the @ctix-declaration directive does not work to include files that are ignored by the exclude option.

The @ctix-declaration directive is designed to work with files that are already included by the include option. Therefore, you need to change your configuration as follows to get the desired result:

```json
{
  "include": [
    "**/*do*",
    "check.ts"
  ],
  "exclude":[
    "check2.ts"
  ]
}
```

**Comment by smallmain** [comment]
> @smallmain
> 
> I tested your reproducible repository, where the include option was set to ["**/_do_"] and the exclude option to ["**check**"]. As a result, the do.ts file was added due to the include option, and the check.ts and check2.ts files were excluded by the exclude option. In this case, the @ctix-declaration directive does not work to include files that are ignored by the exclude option.
> 
> The @ctix-declaration directive is designed to work with files that are already included by the include option. Therefore, you need to change your configuration as follows to get the desired result:
> 
> ```json
> {
>   "include": [
>     "**/*do*",
>     "check.ts"
>   ],
>   "exclude":[
>     "check2.ts"
>   ]
> }
> ```

Not a `check` file, but a `test` file.

You can see that I only included `**/*do*`, but I also included the 'test.js' import.

**Comment by imjuni** [comment]
@smallmain Thank you for your dedicated contribution!

I was fixed this issue in `v2.6.4`.
